# https://docs.github.com/ja/repositories/releasing-projects-on-github/automatically-generated-release-notes#example-configurations
changelog:
  categories:
    - title: 🏕 Features
      labels:
        - '*'
      exclude:
        labels:
          - dependencies
    - title: 👒 Dependencies
      labels:
        - dependencies
