require: rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  Exclude:
    - build/**/*

Lint/AssignmentInCondition:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Style/StderrPuts:
  Enabled: false

Style/GlobalVars:
  Exclude:
    - mrblib/rf/container.rb

Style/SpecialGlobalVars:
  Exclude:
    - mrblib/rf/container.rb

Security/YAMLLoad:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/BlockLength:
  Exclude:
    - mrbgem.rake
    - spec/**/*_spec.rb

Naming/MemoizedInstanceVariableName:
  Exclude:
    - mrblib/rf/container.rb

Naming/MethodName:
  Exclude:
    - mrblib/rf/container.rb

Naming/VariableName:
  Exclude:
    - mrblib/rf/container.rb

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - for

RSpec/DescribeClass:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false
