AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  Exclude:
    - build/**/*

Lint/AssignmentInCondition:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Style/StderrPuts:
  Enabled: false

Security/YAMLLoad:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/BlockLength:
  Exclude:
    - mrbgem.rake

Naming/MemoizedInstanceVariableName:
  Exclude:
    - mrblib/rf/container.rb
