name: Release Action
description: Resuable workflow for release action

inputs:
  github_token:
    description: GitHub token
    required: true
  dockerhub_username:
    description: Docker Hub username
    required: true
  dockerhub_token:
    description: Docker Hub token
    required: true
  version:
    description: Version
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v5
      with:
        submodules: true
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub_username }}
        password: ${{ inputs.dockerhub_token }}
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Build assets
      shell: bash
      run: rake build:assets
    - name: Create release tag
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        VERSION: ${{ inputs.version }}
      run: |
        gh release create $VERSION --generate-notes release/*.tar.gz release/*.zip release/checksums.txt
