name: build and test

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2
    - name: build
      run: rake build:ci
    - name: Upload test binary (linux-amd64)
      uses: actions/upload-artifact@v3
      with:
        name: rf-${{ github.sha }}-linux-amd64
        path: build/linux-amd64/bin/rf
    - name: Upload test binary (darwin-amd64)
      uses: actions/upload-artifact@v3
      with:
        name: rf-${{ github.sha }}-darwin-amd64
        path: build/darwi-amd64/bin/rf

  test-on-linux:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: rf-${{ github.sha }}-linux-amd64
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2
    - name: Install dependencies
      run: bundle install
    - name: Run test
      run: |
        mkdir -p build/bin
        mv build/linux-amd64/bin/rf build/bin/rf
        rake spec

  test-on-macos:
    needs: build
    runs-on: macos-latest
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: rf-${{ github.sha }}-darwin-amd64
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2
    - name: Install dependencies
      run: bundle install
    - name: Run test
      run: |
        mkdir -p build/bin
        mv build/darwin-amd64/bin/rf build/bin/rf
        rake spec
