name: tagpr

on:
  push:
    branches:
      - main

jobs:
  tagpr:
    name: tagpr
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: read
      workflows: write
    steps:
      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        with:
          app-id: ${{ secrets.WORKFLOW_KICKER_APP_ID }
          private-key: ${{ secrets.WORKFLOW_KICKER_PRIVATE_KEY }}
          owner: buty4649
          repositories:
            rf
            homebrew-tap
          permission-contents: write
          permission-pull-requests: write
          permission-issues: read
          permission-workflows: write

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ steps.generate_token.outputs.token }}
          submodules: true

      - uses: Songmu/tagpr@b3fb89424646b06c8aa460f50307c60b6a541425 # v1.17.1
        id: tagpr
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
      - uses: ./.github/actions/release
        if: steps.tagpr.outputs.tag != ''
        with:
          github_token: ${{ steps.generate_token.outputs.token }}
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
          version: ${{ steps.tagpr.outputs.tag }}
